In [1]:
import numpy as numpy
import pandas as pd

Merging 2 dataframes

In [3]:
#DataFrame 1: Employee information
employees = pd. DataFrame({
'employee_id': [1, 2, 3, 4, 5],
'name': ['Jonn', 'Anna', 'Peter', 'Linda', 'Bob'],
'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
'employee_id': [1, 2, 3, 6, 7],
'salary': [60000, 80000, 65000, 70000, 90000],
'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [4]:
employees

   employee_id   name department
0            1   Jonn         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [5]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [7]:
pd.merge(employees,salaries, on='employee_id', how = 'inner')

   employee_id   name department  salary  bonus
0            1   Jonn         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [8]:
pd.merge(employees,salaries, on='employee_id', how = 'outer')

   employee_id   name department   salary    bonus
0            1   Jonn         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [9]:
pd.merge(employees,salaries, on='employee_id', how = 'left')

   employee_id   name department   salary    bonus
0            1   Jonn         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [10]:
pd.merge(employees,salaries, on='employee_id', how = 'right')

   employee_id   name department  salary  bonus
0            1   Jonn         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

Concatenation of 2 dataframes

Joining of 2 dataframes